import type {FormsContent} from '../types';

export const forms: FormsContent = {
  common: {
    optional: 'facultatif',
    required: 'obligatoire',
    previous: 'Précédent',
    next: 'Continuer',
    submit: 'Envoyer',
    sending: 'Envoi en cours…',
    stepLabel: 'Étape {current} sur {total}',
    errorsTitle: 'Vérifiez les informations suivantes',
    honeypotLabel: 'Laissez ce champ vide',
  },
  application: {
    steps: [
      {title: 'Vous', text: 'Qui porte le projet ?'},
      {title: 'Votre activité', text: 'Ce que vous faites déjà.'},
      {title: 'Votre besoin', text: 'Ce que le capital doit permettre.'},
      {title: 'Documents', text: 'Ce qui aide à comprendre.'},
    ],
    fields: {
      firstName: 'Prénom',
      lastName: 'Nom',
      phone: 'Téléphone',
      phoneHint: 'Numéro joignable, WhatsApp de préférence.',
      email: 'Email',
      emailHint: 'Pour recevoir votre accusé de réception.',
      city: 'Ville',
      commune: 'Commune ou quartier',
      businessName: 'Nom de l’activité',
      sector: 'Secteur',
      sectorOther: 'Précisez votre secteur',
      isFormal: 'Mon activité est formalisée (RCCM, registre de commerce)',
      rccm: 'Numéro RCCM',
      foundedYear: 'Année de démarrage',
      employeesCount: 'Nombre de personnes qui travaillent avec vous',
      monthlyRevenueUsd: 'Ventes mensuelles moyennes (USD)',
      description: 'Décrivez votre activité',
      descriptionHint: 'Ce que vous vendez, à qui, où, et ce qui fonctionne le mieux.',
      needType: 'Type de besoin',
      amountUsd: 'Montant souhaité (USD)',
      useOfFunds: 'Utilisation prévue du capital',
      useOfFundsHint: 'Équipements, stock, local, recrutement : soyez concret.',
      files: 'Pièces jointes',
      consent: 'J’autorise LOKAMBE à utiliser ces informations pour étudier mon dossier.',
    },
    sectors: {
      restauration: 'Restauration',
      metiers_de_bouche: 'Métiers de bouche et transformation alimentaire',
      commerce_distribution: 'Commerce et distribution',
      evenementiel: 'Événementiel',
      services: 'Services',
      autre: 'Autre secteur',
    },
    needTypes: {
      croissance: 'Capital de croissance (stock, fonds de roulement)',
      equipements: 'Équipements productifs',
      expansion: 'Expansion (nouveau point de vente, nouvelle activité)',
      autre: 'Autre besoin',
    },
    files: {
      cta: 'Ajouter des fichiers',
      hint: 'PDF, JPG, PNG ou WEBP — 5 fichiers maximum, 10 Mo par fichier.',
      empty: 'Aucun fichier ajouté.',
      remove: 'Retirer {name}',
    },
    review: {
      title: 'Récapitulatif',
      edit: 'Modifier',
    },
    success: {
      title: 'Dossier envoyé',
      text: 'Merci. Votre dossier est enregistré : conservez votre référence pour tout échange avec l’équipe LOKAMBE.',
      referenceLabel: 'Référence de votre dossier',
      next: 'Prochaine étape : nous vérifions votre dossier selon nos critères d’investissement, puis nous vous recontactons.',
      back: 'Revenir à l’accueil',
      demoNotice: 'Démonstration : aucun dossier n’est réellement transmis pour le moment.',
    },
  },
  contact: {
    fields: {
      kind: 'Vous êtes',
      fullName: 'Nom complet',
      organization: 'Organisation',
      email: 'Email',
      phone: 'Téléphone',
      message: 'Votre message',
    },
    kinds: {
      investisseur: 'Investisseur',
      partenaire: 'Partenaire',
      expert: 'Expert',
      entrepreneur: 'Entrepreneur',
      autre: 'Autre',
    },
    success: {
      title: 'Message envoyé',
      text: 'Merci pour votre message. L’équipe LOKAMBE vous répondra à l’adresse indiquée.',
      again: 'Écrire un autre message',
      demoNotice: 'Démonstration : aucun message n’est réellement transmis pour le moment.',
    },
  },
};
