import type {FormsContent} from '../types';

export const forms: FormsContent = {
  common: {
    optional: 'optional',
    required: 'required',
    previous: 'Back',
    next: 'Continue',
    submit: 'Send',
    sending: 'Sending…',
    stepLabel: 'Step {current} of {total}',
    errorsTitle: 'Please check the following',
    honeypotLabel: 'Leave this field empty',
    submitError: {
      title: 'Your submission did not go through',
      invalid:
        'Some of the information was not accepted. Go back through the form, check your answers and your attachments, then try again.',
      tooMany: 'Too many submissions from this device. Wait a few minutes before trying again.',
      server: 'The service is temporarily unavailable. Try again in a few minutes.',
      network: 'The connection was interrupted. Check your network, then try again: nothing was sent.',
    },
  },
  application: {
    steps: [
      {title: 'You', text: 'Who is behind the project?'},
      {title: 'Your business', text: 'What you already do.'},
      {title: 'Your need', text: 'What the capital is for.'},
      {title: 'Documents', text: 'What helps us understand.'},
    ],
    fields: {
      firstName: 'First name',
      lastName: 'Last name',
      phone: 'Phone',
      phoneHint: 'A number we can reach you on, WhatsApp preferably. Write it with the dialling code: +243…',
      email: 'Email',
      emailHint: 'So that we can send you your confirmation.',
      city: 'City',
      commune: 'Commune or neighbourhood',
      businessName: 'Name of the business',
      sector: 'Sector',
      sectorOther: 'Please specify your sector',
      isFormal: 'My business is formally registered (trade register)',
      rccm: 'Trade register number',
      foundedYear: 'Year you started',
      employeesCount: 'Number of people working with you',
      monthlyRevenueUsd: 'Average monthly sales (USD)',
      description: 'Describe your business',
      descriptionHint: 'What you sell, to whom, where, and what works best.',
      needType: 'Type of need',
      amountUsd: 'Amount requested (USD)',
      useOfFunds: 'How the capital would be used',
      useOfFundsHint: 'Equipment, stock, premises, hiring: be concrete.',
      files: 'Attachments',
      consent: 'I allow LOKAMBE to use this information to study my application.',
    },
    sectors: {
      restauration: 'Restaurants and catering',
      metiers_de_bouche: 'Food crafts and processing',
      commerce_distribution: 'Trade and distribution',
      evenementiel: 'Events',
      services: 'Services',
      medias_divertissement: 'Media and entertainment',
      education_formation: 'Education and training',
      autre: 'Another sector',
    },
    needTypes: {
      croissance: 'Growth capital (stock, working capital)',
      equipements: 'Productive equipment',
      expansion: 'Expansion (new point of sale, new activity)',
      autre: 'Another need',
    },
    files: {
      cta: 'Add files',
      hint: 'PDF, JPG, PNG or WEBP — 5 files maximum, 10 MB per file.',
      empty: 'No file added.',
      remove: 'Remove {name}',
    },
    review: {
      title: 'Summary',
      edit: 'Edit',
    },
    success: {
      title: 'Application sent',
      text: 'Thank you. Your application has been recorded: keep your reference for any exchange with the LOKAMBE team.',
      referenceLabel: 'Your application reference',
      next: 'Next step: we review your application against our investment criteria, then we get back to you.',
      back: 'Back to home',
      demoNotice: 'Demonstration: no application is actually being sent for the moment.',
    },
  },
  contact: {
    fields: {
      kind: 'You are',
      fullName: 'Full name',
      organization: 'Organisation',
      email: 'Email',
      phone: 'Phone',
      message: 'Your message',
    },
    kinds: {
      investisseur: 'An investor',
      partenaire: 'A partner',
      expert: 'An expert',
      entrepreneur: 'An entrepreneur',
      autre: 'Other',
    },
    success: {
      title: 'Message sent',
      text: 'Thank you for your message. The LOKAMBE team will reply to the address you gave.',
      again: 'Write another message',
      demoNotice: 'Demonstration: no message is actually being sent for the moment.',
    },
  },
};
